/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import java.awt.print.PrinterException;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author alfinadewi
 */
public class formLaundry extends javax.swing.JFrame {

    /**
     * Creates new form formLaundry
     */
    public formLaundry() {
    
        initComponents();
    }
    
    
    private Connection conn = new Koneksi().Connect();
    
    public int Total_Harga;
    
    //public String kembalian ;
//    int bayar;
//    int total;
//    this.kembalian = bayar - total;
    
    
    public void reset(){
        nama_pelanggan.setText("");
        jenis_cuci.setSelectedItem("pilih");
        harga.setText("");
        berat.setText("");
        total.setText("");
        bayar.setText("");
        kembali.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jenis_cuci = new javax.swing.JComboBox<>();
        bayar = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        transaksi = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        cetak_struk = new javax.swing.JButton();
        berat = new javax.swing.JTextField();
        nama_pelanggan = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        print = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Transaksi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, 40));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 90, 20));

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel3.setText("Harga /kg");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel4.setText("Berat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 90, 20));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 90, 20));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel6.setText("Bayar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 90, 20));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel8.setText("Kembalian");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jenis_cuci.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        jenis_cuci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "Cuci Basah", "Cuci Kering", "Cuci Setrika", "Setrika" }));
        jenis_cuci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_cuciActionPerformed(evt);
            }
        });
        jPanel1.add(jenis_cuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, -1));

        bayar.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 170, -1));

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, -1));

        total.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        transaksi.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        transaksi.setText("Transaksi");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 90, -1));

        batal.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 90, -1));

        cetak_struk.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        cetak_struk.setText("Cetak Struk");
        cetak_struk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_strukActionPerformed(evt);
            }
        });
        jPanel1.add(cetak_struk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, -1));

        berat.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratActionPerformed(evt);
            }
        });
        berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                beratKeyReleased(evt);
            }
        });
        jPanel1.add(berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, -1));

        nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pelangganActionPerformed(evt);
            }
        });
        jPanel1.add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, -1));

        kembali.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 170, -1));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Cuci");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 20));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Laundry\\img\\menum.jpg")); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 450));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 450);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Area.setEditable(false);
        Area.setColumns(20);
        Area.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        Area.setRows(5);
        jScrollPane2.setViewportView(Area);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 340));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 50, 240, 340);

        print.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(640, 400, 80, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Laundry\\img\\login.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(480, 0, 310, 450);

        setSize(new java.awt.Dimension(806, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_bayarActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        String url = "insert into tb_laundry values(?,?,?,?,?,?,?)";
        if(nama_pelanggan.getText().isEmpty() || jenis_cuci.getSelectedItem() == "pilih" || harga.getText().isEmpty() || berat.getText().isEmpty() || total.getText().isEmpty() || bayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Lengkapi Form terlebih dahulu");
        }else{
            int Bayar = Integer.parseInt(bayar.getText());
            int Total_Harga = Integer.parseInt(total.getText());
            int kembalian = Bayar - Total_Harga ;
            kembali.setText(String.valueOf(kembalian));
            try {
                PreparedStatement stat = conn.prepareStatement(url);
                stat.setString(1, String.valueOf(nama_pelanggan.getText()));
                stat.setString(2, (String) jenis_cuci.getSelectedItem());
                stat.setString(3, harga.getText());
                stat.setString(4, berat.getText());
                stat.setString(5, total.getText());
                stat.setString(6, bayar.getText());
                stat.setString(7, String.valueOf(kembalian));
                stat.executeUpdate();
                //JOptionPane.showMessageDialog(null, "Kembalian :\n"+kembalian);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Transaksi Gagal"+e);
            }
        }
    }//GEN-LAST:event_transaksiActionPerformed

    private void jenis_cuciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_cuciActionPerformed
        if(jenis_cuci.getSelectedItem().equals("pilih")){
            harga.setText("0");
        }else if(jenis_cuci.getSelectedItem().equals("Cuci Basah")){
            harga.setText("3000");
        }else if(jenis_cuci.getSelectedItem().equals("Cuci Kering")){
            harga.setText("4000");
        }else if(jenis_cuci.getSelectedItem().equals("Cuci Setrika")){
            harga.setText("5000");
        }else if(jenis_cuci.getSelectedItem().equals("Setrika")){
            harga.setText("3000");
        }
    }//GEN-LAST:event_jenis_cuciActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        reset();
    }//GEN-LAST:event_batalActionPerformed

    private void beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beratKeyReleased
        if(berat.getText().equals("")){
            total.setText("0");
            
        }else{
            int Harga = Integer.parseInt(harga.getText());
            int Berat = Integer.parseInt(berat.getText());
            Total_Harga = Harga*Berat;
            total.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_beratKeyReleased

    private void nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pelangganActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
        try {
            Area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(formStruk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void cetak_strukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_strukActionPerformed
        // TODO add your handling code here:
        
        Area.setText               (" --------------------------------\n");
        Area.setText(Area.getText()+"          Bunda Laundry          \n");
        Area.setText(Area.getText()+" --------------------------------\n");
        
        java.util.Date obj = new java.util.Date();
        String date = obj.toString();
        
        Area.setText(Area.getText()+"\n   "+date+"\n\n\n");
        
        Area.setText(Area.getText()+" Nama           :    "+nama_pelanggan.getText()+"\n\n");
        Area.setText(Area.getText()+" Jenis Cuci     :    "+jenis_cuci.getSelectedItem()+"\n\n");
        Area.setText(Area.getText()+" Harga /kg      :    "+harga.getText()+"\n\n");
        Area.setText(Area.getText()+" Berat          :    "+berat.getText()+"\n\n");
        
        Area.setText(Area.getText()+" --------------------------------\n");
        
        Area.setText(Area.getText()+"\n");
        Area.setText(Area.getText()+" Total          :    "+total.getText()+"\n\n");
        Area.setText(Area.getText()+" Bayar          :    "+bayar.getText()+"\n\n");
        Area.setText(Area.getText()+" Kembalian      :    "+kembali.getText()+"\n");

        Area.setText(Area.getText()+"\n");
        Area.setText(Area.getText()+"                     ");
                                                        
    }//GEN-LAST:event_cetak_strukActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        
//        int Total_Harga,Bayar,kembalii; //nama variabel
//        
//        //input
//        Total_Harga = Integer.parseInt(total.getText());
//        Bayar = Integer.parseInt(bayar.getText());
//        
//        //rumus hitung
//        kembalii = Total_Harga - Bayar;
//        
//        //output
//        kembali.setText(String.valueOf(kembalii));
        
        
    }//GEN-LAST:event_kembaliActionPerformed

    private void beratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton batal;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField berat;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cetak_struk;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis_cuci;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JButton print;
    private javax.swing.JTextField total;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
